//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ 生成的包含文件。
// 供 BookManage.rc 使用
//
#define IDCANCEL2                       3
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDD_BOOKMANAGE_DIALOG           102
#define IDR_MAINFRAME                   128
#define IDD_LOGIN_DIALOG                129
#define IDR_MAINMENU                    130
#define IDD_STOCK_DIALOG                139
#define IDR_STOCKMENU                   140
#define IDD_STOCK_DIALOG1               141
#define IDD_STOCK_DIALOG2               142
#define IDD_REFUND_DIALOG               143
#define IDD_REFUND_DIALOG1              144
#define IDD_REFUND_DIALOG2              145
#define IDD_STASTIC_DIALOG              146
#define IDD_DATA_DIALOG                 146
#define IDD_STASTIC_DIALOG1             147
#define IDD_VEND_DIALOG2                147
#define IDD_STASTIC_DIALOG2             148
#define IDD_DATA_DIALOG1                148
#define IDD_STASTIC_DIALOG3             149
#define IDD_DATA_DIALOG2                149
#define IDD_VEND_DIALOG                 150
#define IDR_STASTICMENU                 151
#define IDR_REFUNDMENU                  152
#define IDR_VENDMENU                    153
#define IDD_VEND_DIALOG1                154
#define IDB_GUARD                       158
#define IDB_FLOWER                      159
#define IDB_COD                         160
#define IDR_ACCELERATOR1                165
#define IDD_VEND_DIALOG3                167
#define IDD_DIALOG_USER_INFO            171
#define IDD_DIALOG_NEW_USERNAME         173
#define IDD_DIALOG_NEW_PASSWORD         175
#define IDD_DIALOG_CREATE               177
#define IDD_DIALOG_BACKUP               180
#define IDD_DIALOG_SAVE                 182
#define IDD_DIALOG_SAVE1                183
#define IDD_DIALOG_LOAD                 183
#define IDC_NAME                        1000
#define IDC_CODE                        1001
#define IDC_QUIT                        1002
#define IDC_OK                          1003
#define IDC_STOCK_TAB                   1004
#define IDC_OPERA_STATIC                1007
#define IDC_TIME_STATIC                 1008
#define IDC_STOCK_LIST                  1011
#define IDC_SUPPLY_LIST                 1013
#define IDC_STOCK_NAME                  1014
#define IDC_STOCK_SUPPLY                1015
#define IDC_STOCK_PRICE                 1016
#define IDC_STOCK_COUNT                 1017
#define IDC_STOCK_ISBN                  1018
#define IDC_STOCK_AUTHOR                1019
#define IDC_REFUND_TAB                  1020
#define IDC_REFUND_LIST                 1021
#define IDC_REFUND_ISBN                 1022
#define IDC_REFUND_NAME                 1023
#define IDC_REFUND_COUNT                1024
#define IDC_REFUND_ENTER                1025
#define IDC_REFUND_CLEAR                1026
#define IDC_STASTIC_TAB                 1027
#define IDC_VEND_LIST                   1028
#define IDC_VENDBYDAY_LIST              1029
#define IDC_VENDBYMONTH_LIST            1029
#define IDC_VENDS_LIST                  1030
#define IDC_STORAGE_LIST                1031
#define IDC_PUCHE_LIST                  1035
#define IDC_PUCHECOUNT                  1037
#define IDC_CANCEL                      1039
#define IDC_EDIT_ISBN                   1040
#define IDC_BUTTON_FIND                 1041
#define IDC_EDIT_BOOKNAME               1042
#define IDC_EDIT_AUTHOR                 1043
#define IDC_EDIT_C                      1044
#define IDC_BUTTON_STOCK                1048
#define IDC_BUTTON_REFUND               1049
#define IDC_STATIC_NAME                 1049
#define IDC_BUTTON_VEND                 1050
#define IDC_STATIC_PASS                 1050
#define IDC_BUTTON_DATA                 1051
#define IDC_STATIC_RANK                 1051
#define IDC_BUTTON_CHANGE_USERNAME      1052
#define IDC_BUTTON_USER                 1052
#define IDC_BUTTON_PASS                 1053
#define IDC_BUTTON_BACKUP               1053
#define IDC_BUTTON_REGISTER             1054
#define IDC_EDIT_NEW_NAME               1056
#define IDC_EDIT_NEW_PASS               1057
#define IDC_EDIT_USER                   1058
#define IDC_EDIT_PASS                   1059
#define IDC_COMBO_RANK                  1061
#define IDC_BUTTON_STOCK_ADD            1062
#define IDC_BUTTON_STOCK_SUB            1063
#define IDC_BUTTON_STOCK_SAVE           1064
#define IDC_BUTTON_STOCK_QUERY          1065
#define IDC_BUTTON_STOCK_CONFIRM        1066
#define IDC_BUTTON_CLEAR                1067
#define IDC_BUTTON_RESTORE              1069
#define IDC_BUTTON_SAVE                 1070
#define IDC_STATIC_PATH                 1070
#define IDC_BUTTON_SAVE_PATH            1071
#define IDC_BUTTON_SAVE_START           1072
#define IDC_STATIC_PATH_LOAD            1073
#define IDC_BUTTON_LOAD_PATH            1074
#define IDC_BUTTON_LOAD_START           1075
#define ID_ABOUT                        32771
#define ID_EXIT                         32772
#define ID_SUPPLY_PRICE                 32775
#define ID_STOCK_RECORD                 32776
#define ID_REFUND_RECORD                32777
#define ID_REFUND_OPERA                 32778
#define ID_VEND_BYDAY                   32779
#define ID_VEND_LIST                    32780
#define ID_VEND_RECORD                  32781
#define ID_VEND_CONSOLE                 32782
#define ID_ADD_SUPPLY                   32783
#define ID_MINU_SUPPLY                  32784
#define ID_CHOOSE_SUPPLY                32785
#define ID_PRINT                        32787
#define ID_PRINTVIEW                    32788
#define ID_ADDBOOK                      32789
#define ID_MINUSBOOK                    32790
#define ID_PUCHE                        32791
#define ID_CLEAR                        32793
#define ID_SAVE                         32794
#define ID_DISPLAY                      32795
#define ID_ADDOPERA                     32797
#define ID_VEND_BYMONTH                 32798
#define ID_EDIT_MONTH                   32799
#define ID__32800                       32800
#define ID__RANK                        32801
#define ID_MONTH                        32802
#define ID_RANK                         32803
#define ID_32813                        32813
#define ID_FIND                         32814
#define ID_32815                        32815
#define ID_USER                         32816
#define ID_32817                        32817
#define ID_REFRESH                      32818
#define ID_32819                        32819
#define ID_REFRESH_DATA                 32820

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        184
#define _APS_NEXT_COMMAND_VALUE         32821
#define _APS_NEXT_CONTROL_VALUE         1076
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
